DROP TABLE IF EXISTS genres CASCADE;
DROP TABLE IF EXISTS mpa CASCADE;
DROP TABLE IF EXISTS films CASCADE;
DROP TABLE IF EXISTS films_genres CASCADE;
DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS likes CASCADE;
DROP TABLE IF EXISTS friends CASCADE;

CREATE TABLE mpa
(
    mpa_id_in_mpa INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    mpa_name varchar(40)
);

CREATE TABLE films
(
    film_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    film_name varchar(40) NOT NULL,
    description varchar(200),
    release_date DATE,
    duration int,
    mpa_id_in_film int REFERENCES mpa(mpa_id_in_mpa)
);

CREATE TABLE genres
(
    genre_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    genre_name varchar(40)
);

create table FILMS_GENRES
(
    FILM_ID  INTEGER
        references FILMS
            on delete cascade,
    GENRE_ID INTEGER
        references GENRES
            on delete cascade
);



CREATE TABLE users
(
    user_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email varchar(40),
    login varchar(40) NOT NULL,
    name varchar(40),
    birthday DATE
);

create table LIKES
(
    FILM_ID INTEGER
        references FILMS
            on delete cascade,
    USER_ID INTEGER
        references USERS
            on delete cascade
);


create table FRIENDS
(
    FIRST_USER_ID  INTEGER
        references USERS
            on delete cascade,
    SECOND_USER_ID INTEGER
        references USERS
            on delete cascade
);






