DROP TABLE IF EXISTS genres CASCADE;
DROP TABLE IF EXISTS mpa CASCADE;
DROP TABLE IF EXISTS films CASCADE;
DROP TABLE IF EXISTS films_genres CASCADE;
DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS likes CASCADE;
DROP TABLE IF EXISTS friends CASCADE;
DROP TABLE IF EXISTS directors CASCADE;
DROP TABLE IF EXISTS films_directors CASCADE;

CREATE TABLE mpa
(
    mpa_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    mpa_name varchar(40)
);

CREATE TABLE films
(
    film_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    film_name varchar(40) NOT NULL,
    description varchar(200),
    release_date DATE,
    duration int,
    mpa_id int REFERENCES mpa(mpa_id)
);

CREATE TABLE genres
(
    genre_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    genre_name varchar(40)
);

create table films_genres
(
    film_id  INTEGER
        references films
            on delete cascade,
    genre_id INTEGER
        references genres
            on delete cascade
);

CREATE TABLE users
(
    user_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email varchar(40),
    login varchar(40) NOT NULL,
    name varchar(40),
    birthday DATE
);

create table likes
(
    film_id INTEGER
        references films
            on delete cascade,
    user_id INTEGER
        references users
            on delete cascade
);

create table friends
(
    first_user_id  INTEGER
        references users
            on delete cascade,
    second_user_id INTEGER
        references users
            on delete cascade
);

CREATE TABLE directors
(
    director_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    director_name varchar(60)
);

CREATE TABLE films_directors
(
    film_id int REFERENCES films(film_id) ON DELETE CASCADE,
    director_id int REFERENCES directors(director_id) ON DELETE CASCADE
);

INSERT INTO mpa (mpa_name)
VALUES ('G'),
       ('PG'),
       ('PG-13'),
       ('R'),
       ('NC-17');

INSERT INTO genres (genre_name)
VALUES ('Комедия'),
       ('Драма'),
       ('Мультфильм'),
       ('Триллер'),
       ('Документальный'),
       ('Боевик');

INSERT INTO users (email, login, name, birthday)
VALUES ('email@mail.ru', 'mailru', 'mail', '1999-10-06'),
       ('email@yandex.ru', 'yandexru', 'yandex', '2000-11-04'),
       ('email@rambler.ru', 'ramblerru', 'rambler', '1996-05-20'),
       ('email@google.com', 'google.com', 'google', '2001-01-22');

INSERT INTO friends (first_user_id, second_user_id)
VALUES (1, 2), (1, 3), (2, 3), (2, 4), (4, 3);

INSERT INTO films (film_name, description, release_date, duration, mpa_id)
VALUES ('Железный человек', 'Четкий фильм', '2021-05-15', 120, 1),
       ('Тор', 'Молот', '2022-06-15', 110, 2),
       ('Человек муравей', 'насекомый', '2012-05-15', 111, 3),
       ('Флеш', 'Не Марвел', '2020-04-15', 105, 4),
       ('Мстители', 'Все лучшие', '2015-03-15', 103, 1);

INSERT INTO films_genres (film_id, genre_id)
VALUES (1, 2), (1, 3), (2, 3), (2, 4), (4, 3);

INSERT INTO likes (film_id, user_id)
VALUES (1, 2), (1, 3), (3, 3), (2, 4), (4, 3);

INSERT INTO directors (director_name)
VALUES ('Стивен Спилберг'),
       ('Федор Бондарчук'),
       ('Тимур Бекмамбетов'),
       ('Андрей Звягинцев'),
       ('Юрий Быков'),
       ('Квентин Тарантино');

INSERT INTO films_directors (film_id, director_id)
VALUES (1, 1), (2, 1), (3, 2), (5, 1), (4, 2);

